#!/bin/bash -e

# TODO Allow passing in merge strategy

current_commit="$(git rev-parse HEAD)"
commit="$(git rev-parse "$1")"

git stash -u
trap EXIT 'git reset --hard "$current_commit" && git stash pop'
git checkout "$commit^"
git merge $(non-first-merge-parents "$commit")
git commit -a --allow-empty{,-message}
git show "$(git commit-tree "$commit" -p HEAD -C "$commit")"
