#!/bin/bash

normal_background="$(tput sgr0)"
red_background="$(tput setab 1)"
green_background="$(tput setab 2)"

diff -u <(hlcat "$1") <(hlcat "$2") |
	sed 's/^\(+.*\)$/'"$green_background"'\1'"$normal_background"/ |
	sed 's/^\(-.*\)$/'"$red_background"'\1'"$normal_background"/
